AcademiaSoft/Models/BoletaNotas.cs
using System.ComponentModel.DataAnnotations;

namespace AcademiaSoft.Models
{
    public class BoletaNotas
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Matricula")]
        [Required(ErrorMessage = "La Matricula es requerida.")]
        [Range(1,10,ErrorMessage ="Debes seleccionar una matricula")]
        public int Idmatricula { get; set; }

        [Display(Name ="Cargo")]
        [Required(ErrorMessage = "El Cargo es requerida.")]
        [Range(1, 10, ErrorMessage = "")]
        public int Idcargo { get; set; }

        [Required(ErrorMessage ="La Primera nota es requerida.")]
        [RegularExpression("(^[0-20]+$)", ErrorMessage = "Solo se permiten números")]
        public decimal? Nota1 { get; set; }

        [Required(ErrorMessage = "La Segunda nota es requerida.")]
        [RegularExpression("(^[0-20]+$)", ErrorMessage = "Solo se permiten números")]
        public decimal? Nota2 { get; set; }

        [Required(ErrorMessage = "La Tercera nota es requerida.")]
        [RegularExpression("(^[0-20]+$)", ErrorMessage = "Solo se permiten números")]
        public decimal? Nota3 { get; set; }

        [Required(ErrorMessage = "La Cuarta nota es requerida.")]
        [RegularExpression("(^[0-20]+$)", ErrorMessage = "Solo se permiten números")]
        public decimal? Nota4 { get; set; }
        
        public decimal? Promedio { get; set; }

        public BoletaNotas()
        {
            Promedio = 0;
        }
    }
}

AcademiaSoft/Controllers/BoletaNotasController.cs
using AcademiaSoft.Dao;
using AcademiaSoft.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaSoft.Controllers
{
    public class BoletaNotasController : Controller
    {
        BoletaNotasDao boletaNotasDao = new BoletaNotasDao();
        AlumnoDao alumnoDao = new AlumnoDao();
        AulaDao aulaDao = new AulaDao();
        MatriculaDao matriculaDao = new MatriculaDao();

        CargoProfesorDao cargoProfesorDao = new CargoProfesorDao();
        CursoDao cursoDao = new CursoDao();
        ProfesorDao ProfesorDao = new ProfesorDao();
        PeriodoDao periodoDao = new PeriodoDao();

        // GET: BoletaNotasController
        public ActionResult Index()
        {
            try
            {
                ViewBag.delete = TempData["eliminar_mensanje"];
                ViewBag.save = TempData["registrar_mensanje"];
                ViewBag.update = TempData["actualizar_mensanje"];
                ViewBag.error = TempData["error_mensanje"];
            }
            catch (Exception ex) { }
            
            ViewBag.CargoProfesor = cargoProfesorDao.ListarProfesorBoleta(0, "");
            ViewBag.Curso = cursoDao.ListarCurso();
            ViewBag.Aula = aulaDao.Listar();
            ViewBag.Alumno = alumnoDao.ListarAlumnos();
            ViewBag.Profesor = ProfesorDao.ListarProfesor();
            ViewBag.Periodo = periodoDao.Listar();

            return View();
        }
        
        [HttpPost]
        public async Task<JsonResult> Registrar([FromBody] List<BoletaNotas> boleta)
        {
            foreach (var item in boleta)
            {
                boletaNotasDao.Validar_Promedio(item);
            }
            return Json(boleta);
        }


        public ActionResult Edit(int id)
        {
            if (id != null || id>0)
            {
                ViewBag.Notas = boletaNotasDao.Listar(id);
                

                if (ViewBag.Notas.Count > 0)
                {
                    ViewBag.CargoProfesor = cargoProfesorDao.Listar();
                    ViewBag.Curso=cursoDao.ListarCurso();
                    ViewBag.Matricula = matriculaDao.ListarAlumnoMatricula();
                    ViewBag.Alumno = alumnoDao.ListarAlumnos();
                    ViewBag.Profesor=ProfesorDao.ListarProfesor();

                    foreach (var boleta in ViewBag.Notas)
                    {
                        foreach (var cargo in ViewBag.CargoProfesor)
                        {
                            if (boleta.Idcargo == cargo.Id)
                            {
                                foreach (var curso in ViewBag.Curso)
                                {
                                    if (cargo.Idcurso == curso.Id)
                                    {
                                        ViewBag.Titulo = curso.Descripcion;
                                    }
                                }

                                foreach (var profesor in ViewBag.Profesor)
                                {
                                    if (cargo.Idprofesor == profesor.Id)
                                    {
                                        ViewBag.Docente = profesor.Apellido + " "+profesor.Nombre;
                                    }
                                }
                            }
                        }
                    }

                    return View();
                }
                TempData["error_mensanje"] = "Error no existe una boleta de nota";
                ViewBag.error = TempData["error_mensanje"];
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        

        // POST: BoletaNotasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

       
    }
}

AcademiaSoft/Views/BoletaNotas/Edit.cshtml
@{
    ViewData["Title"] = "Notas | Editar";
}
@model AcademiaSoft.Models.BoletaNotas

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Notas | Editar</h1>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container-fluid">
        <div class="card shadow-lg p-3 mb-5 bg-body rounded">
            <div class="card-header">
                <h5 style="float:left">
                    <strong>Profesor:</strong> @ViewBag.Docente
                </h5>
                <h5 style="float:left; padding:0px 0px 0px 10px;">
                    <strong>Materia:</strong> @ViewBag.Titulo
                </h5>
                <spam style="float:right">Total:  @ViewBag.Notas.Count </spam>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Alumno</th>
                            <th>1°</th>
                            <th>2°</th>
                            <th>3°</th>
                            <th>4°</th>
                        </tr>
                    </thead>
                    <tbody id="notas-boletas">
                        @foreach (var boleta in ViewBag.Notas)
                        {
                        <tr>
                            <td><input type="hidden" asp-for="Id" value="@boleta.Id" /></td>
                            <td>
                                    @foreach (var matricula in ViewBag.Matricula)
                                    {
                                        @if (boleta.Idmatricula == matricula.Id)
                                        {
                                            @foreach (var alumno in ViewBag.Alumno)
                                            {
                                                @if (matricula.Idalumno == alumno.Id)
                                                {
                                                    @alumno.Apellido @alumno.Nombre
                                                }
                                            }
                                        }

                                    }
                            </td>
                                <td><input type="number" min="0" max="20" pattern="[0-20]+" asp-for="Nota1" class="form-control" value="@boleta.Nota1" /></td>
                                <td><input type="number" min="0" max="20" pattern="[0-20]+" asp-for="Nota2" class="form-control" value="@boleta.Nota2" /></td>
                                <td><input type="number" min="0" max="20" pattern="[0-20]+" asp-for="Nota3" class="form-control" value="@boleta.Nota3" /></td>
                                <td><input type="number" min="0" max="20" pattern="[0-20]+" asp-for="Nota4" class="form-control" value="@boleta.Nota4" /></td>
                        </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6">
                                <div style="float:right;">
                                    <a asp-action="Index" asp-controller="BoletaNotas" class="btn btn-default">Salir</a>
                                    <button type="submit" class="btn btn-success boleta-notas" onclick="Guardar()">Guardar Notas</button>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                    
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    
    <script src="~/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script>
        //$('.boleta-notas').click(async function (e) {
        const Guardar = async () => {
            var datos = []

            $("#notas-boletas tr").each(function () {
                var informacion = {};
                //informacion.codigo = $($(this).find('td:eq(0) input')).val();
                informacion.Id = $($(this).find('td:eq(0) input')).val();
                informacion.Idmatricula=1;
                informacion.Idcargo=2;
                informacion.Nota1 = $($(this).find('td:eq(2) input')).val();
                informacion.Nota2 = $($(this).find('td:eq(3) input')).val();
                informacion.Nota3 = $($(this).find('td:eq(4) input')).val();
                informacion.Nota4 = $($(this).find('td:eq(5) input')).val();

                datos.push(informacion);
            });

            console.log(datos)
            console.log(JSON.stringify(datos))
            
            try {
                const response = await fetch('@Url.Action("Registrar","BoletaNotas")', { method: 'POST', headers: { 'Content-Type': 'application/json;charset=UTF-8' }, body: JSON.stringify(datos) })
                const data = await response.json()

                console.log(data)
            } catch (err) {
                console.log(err)
            }


        }

    </script>
    <script src="~/js/boleta/index.js"></script>
    
}

AcademiaSoft/Views/BoletaNotas/Index.cshtml
@{
    ViewData["Title"] = "Notas";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Detalles de la Notas</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-md-right">
                    <a href="@Url.Action("Edit","BoletaNotas", new{ id=26 })" class="btn btn-primary"><i class="fas fa-edit"></i>Registrar Notas</a>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container-fluid">
        <div class="row g-2 justity-content-center">
            <div class="col-lg-4 col-md-3 col-12">
                <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                    <form>
                        <div class="card-body">
                            <label>Profesor / Materia</label>
                            <div class="form-group">
                                <select class="form-control">
                                    <option>-- Seleccione la Materia --</option>
                                    
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Fecha</label>
                                <input type="date" class="form-control" />
                            </div>
                            <button class="btn btn-outline-warning" type="submit">Buscar</button>
                        </div>

                    </form>
                </div>
            </div>

            <div class="col-lg-8 col-md-7 col-12">
                <div class="card shadow-lg p-3 mb-5 bg-body rounded">
                    @if (@ViewBag.delete != null)
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>@ViewBag.delete</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                    @if (@ViewBag.error != null)
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>Error: </strong>@ViewBag.error
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                    @if (@ViewBag.save != null)
                    {
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>@ViewBag.save</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                    @if (@ViewBag.update != null)
                    {
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            <strong>@ViewBag.update</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                    <div class="table-response">
                        <table class="table table-bordered" id="informacion_notas">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Aula y Materia</th>
                                    <th>Total</th>
                                    <th>Años</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var cargo in ViewBag.CargoProfesor)
                                {
                                    <tr>
                                        <td></td>
                                        <td>
                                            @foreach (var aula in ViewBag.Aula)
                                            {
                                                @if (aula.Id==cargo.Idaula)
                                                {
                                                    @aula.Descripcion
                                                }
                                            }

                                            @foreach(var curso in ViewBag.Curso){
                                                @if(curso.Id == cargo.Idcurso){
                                                    @curso.Descripcion
                                                }
                                            }

                                        </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script src="~/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

}