AcademiaSoft/Controllers/AlumnoController.cs
using AcademiaSoft.Dao;
using AcademiaSoft.Models;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaSoft.Controllers
{
    public class AlumnoController : Controller
    {
        AlumnoDao alumnodao=new AlumnoDao();
        UsuarioDao usuariodao=new UsuarioDao();
        
        public ActionResult Index()
        {
            try
            {
                ViewBag.delete = TempData["eliminar_mensanje"];
                ViewBag.save = TempData["registrar_mensanje"];
                ViewBag.update = TempData["actualizar_mensanje"];
            }
            catch (Exception ex) { }

            var alumnos = alumnodao.ListarAlumnos();
            var usuarios = usuariodao.ListarUsuarios();

            return View(new {alumnos, usuarios });
        }

        // GET: AlumnoController/Create
        public ActionResult Create()
        {
            ViewBag.Usuarios = usuariodao.ListarUsuarios();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                alumnodao.Guardar(alumno);
                TempData["registrar_mensanje"] = "Se Registro Correctamente";
                ViewBag.save = TempData["registrar_mensanje"];
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Usuarios = usuariodao.ListarUsuarios();
            return View(alumno);
        }


        // GET: AlumnoController/Edit/5
        public ActionResult Edit(int id)
        {
            Alumno alumno = alumnodao.Buscar(id);
            if (alumno != null)
            {   
                ViewBag.Usuarios = usuariodao.ListarUsuarios();
                return View(alumno);
            }
            return RedirectToAction(nameof(Index));
            
        }

        // POST: AlumnoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Alumno alumno)
        {
            if(ModelState.IsValid)
            {
                TempData["actualizar_mensanje"] = "Se Actualizo Correctamente.";
                ViewBag.update = TempData["actualizar_mensanje"];
                alumnodao.Actualizar(alumno);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Usuarios = usuariodao.ListarUsuarios();
            return View(alumno);
        }

        // GET: AlumnoController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Alumno alumno = alumnodao.Buscar(id);
            if (id==null || alumno==null)
            {
                return NotFound();
            }
            TempData["eliminar_mensanje"] = "Se Elimino Correctamente el Alumno.";
            ViewBag.delete = TempData["eliminar_mensanje"];
            alumnodao.Eliminar(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

AcademiaSoft/Controllers/AulaController.cs
using AcademiaSoft.Dao;
using AcademiaSoft.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaSoft.Controllers
{
    public class AulaController : Controller
    {
        AulaDao auladao=new AulaDao();
        public ActionResult Index()
        {
            try
            {
                ViewBag.delete = TempData["eliminar_mensanje"];
                ViewBag.save = TempData["registrar_mensanje"];
                ViewBag.update = TempData["actualizar_mensanje"];
                ViewBag.error = TempData["error_mensanje"];
            }
            catch (Exception ex) { }
            var aula=auladao.Listar();
            return View(aula);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aula aula)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["registrar_mensanje"] = "Se Registro Correctamente";
                    ViewBag.save = TempData["registrar_mensanje"];
                    auladao.Guardar(aula);
                    return RedirectToAction(nameof(Index));
                }
                return View(aula);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            Aula aula_existe = auladao.Buscar(id);
            if (id !=null && aula_existe != null)
            {
                return View(aula_existe);
            }
            TempData["error_mensanje"] = "El Aula no existe en el Sistema.";
            ViewBag.error = TempData["error_mensanje"];
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Aula aula)
        {
            try
            {
                Aula aula_existe = auladao.Buscar(id);
                if (id != null && aula_existe != null)
                {
                    if (ModelState.IsValid)
                    {
                        TempData["actualizar_mensanje"] = "Se Actualizo Correctamente.";
                        ViewBag.update = TempData["actualizar_mensanje"];
                        auladao.Actualizar(aula);
                        return RedirectToAction(nameof(Index));
                    }
                    return View(aula);
                }
                TempData["error_mensanje"] = "El Aula no existe en el Sistema.";
                ViewBag.error = TempData["error_mensanje"];
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Aula aula = auladao.Buscar(id);
            if (id == null || aula ==null)
            {
                return NotFound();
            }
            var mensaje = auladao.Eliminar(id);
            TempData["eliminar_mensanje"] = "" + mensaje + "";
            ViewBag.delete = TempData["eliminar_mensanje"];
            return RedirectToAction(nameof(Index));
        }

        // POST: AulaController/Delete/5
        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
         */
    }
}

AcademiaSoft/Controllers/PeriodoController.cs
using AcademiaSoft.Dao;
using AcademiaSoft.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaSoft.Controllers
{
    public class PeriodoController : Controller
    {
        PeriodoDao periododao =new PeriodoDao();
        public ActionResult Index()
        {
            try
            {
                ViewBag.delete = TempData["eliminar_mensanje"];
                ViewBag.save = TempData["registrar_mensanje"];
                ViewBag.update = TempData["actualizar_mensanje"];
            }
            catch (Exception ex) { }
            return View(periododao.Listar());
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Periodo periodo)
        {
            if (ModelState.IsValid)
            {
                periododao.Guardar(periodo);
                TempData["registrar_mensanje"] = "Se Registro Correctamente";
                ViewBag.save = TempData["registrar_mensanje"];
                return RedirectToAction(nameof(Index));
            }
            return View(periodo);
        }

        public ActionResult Edit(int id)
        {
            Periodo periodo=periododao.Buscar(id);
            if (id !=null && periodo!= null)
            {
                return View(periodo);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Periodo periodo)
        {
            Periodo Validar_Periodo = periododao.Buscar(id);
            if (Validar_Periodo != null)
            {
                if (ModelState.IsValid)
                {
                    TempData["actualizar_mensanje"] = "Se Actualizo Correctamente.";
                    ViewBag.update = TempData["actualizar_mensanje"];
                    periododao.Actualizar(periodo);
                    return RedirectToAction(nameof(Index));
                }
                return View(periodo);
            }
            return NotFound();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Periodo periodo = periododao.Buscar(id);
            if (id != null && periodo != null)
            {
                var mensaje= periododao.Eliminar(id);
                TempData["eliminar_mensanje"] = ""+mensaje+"";
                ViewBag.delete = TempData["eliminar_mensanje"];
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        
    }
}

AcademiaSoft/Controllers/UsuarioController.cs
using AcademiaSoft.Dao;
using AcademiaSoft.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AcademiaSoft.Controllers
{
    public class UsuarioController : Controller
    {
        UsuarioDao usuariodao = new UsuarioDao();

        public ActionResult Index()
        {
            try
            {
                ViewBag.delete = TempData["eliminar_mensanje"];
                ViewBag.save = TempData["registrar_mensanje"];
                ViewBag.update = TempData["actualizar_mensanje"];
            }
            catch (Exception ex) { }
            var usuario=usuariodao.ListarUsuarios();
            return View(usuario);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuariodao.Guardar(usuario);
                TempData["registrar_mensanje"] = "Se Registro Correctamente";
                ViewBag.save = TempData["registrar_mensanje"];
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        public ActionResult Edit(int id)
        {
            Usuario usuario=usuariodao.Buscar(id);
            if (usuario != null && id!=null)
            {
                return View(usuario);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int Id, Usuario usuario)
        {
            Usuario user=usuariodao.Buscar(Id);
            if (user != null && Id!=null)
            {
                if (ModelState.IsValid)
                {
                    TempData["actualizar_mensanje"] = "Se Actualizo Correctamente.";
                    ViewBag.update = TempData["actualizar_mensanje"];
                    usuariodao.Actualizar(usuario);
                    return RedirectToAction(nameof(Index));
                }
                return View(usuario);
            }
            return NotFound();
            
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Usuario user = usuariodao.Buscar(id);
            if (user != null && id != null)
            {
                TempData["eliminar_mensanje"] = "Se Elimino Correctamente el Alumno.";
                ViewBag.delete = TempData["eliminar_mensanje"];
                usuariodao.Eliminar(id);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        
    }
}

AcademiaSoft/Views/Shared/View.cshtml
@model IEnumerable<AcademiaSoft.Models.BoletaNotas>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idmatricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idcargo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Promedio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idmatricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idcargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Promedio)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AcademiaSoft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</head>


<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="@Url.Action("Index","Home")" class="brand-link">
                <img src="" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Academia Soft</span>
            </a>

            <div class="sidebar">
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Home")" class="nav-link">
                                <i class="fas fa-tachometer-alt"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Registros
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Index","Alumno")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Alumnos</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index","Usuario")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Usuarios</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index","Aula")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Aula</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index","Periodo")" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Periodo</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","BoletaNotas")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Notas
                                    <!--<span class="right badge badge-danger">New</span> -->
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Layout Options
                                    <i class="fas fa-angle-left right"></i>
                                    <span class="badge badge-info right">6</span>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/layout/top-nav.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Top Navigation</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/top-nav-sidebar.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Top Navigation + Sidebar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/boxed.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Boxed</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/fixed-sidebar.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Fixed Sidebar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/fixed-sidebar-custom.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Fixed Sidebar <small>+ Custom Area</small></p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/fixed-topnav.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Fixed Navbar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/fixed-footer.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Fixed Footer</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/layout/collapsed-sidebar.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Collapsed Sidebar</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Charts
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>ChartJS</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Flot</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Inline</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/uplot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>uPlot</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    UI Elements
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/UI/general.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>General</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/icons.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Icons</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/buttons.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Buttons</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/sliders.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Sliders</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/modals.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Modals & Alerts</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/navbar.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Navbar & Tabs</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/timeline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Timeline</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/UI/ribbons.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Ribbons</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>

        <div class="content-wrapper">
            @RenderBody()
        </div>
        
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>
    </div>

    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/dist/js/adminlte.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>